const types = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  RESET_CART: "RESET_CART",
  SUMAR_CART: "SUMAR_CART",
  ACTIVAR_MODAL: "ACTIVAR_MODAL",
  DESACTIVAR_MODAL: "DESACTIVAR_MODAL" 
}
export default types;
